name: Maven Tests with Headless Chrome

on:
  push:
    branches:
      - master # Trigger the workflow on push events to the master branch
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Maven Tests
        run: mvn test -Pweb
        env:
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 4444