name: Daily Java Tests

on:
  schedule:
    # Schedule the workflow to run at 10:00 AM UTC every day
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.4-openjdk-11 # Use a Docker image with Maven and OpenJDK 11

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Maven Tests
        run: mvn test -Pweb